export const formattedCountries = [
    {"name":"Afghanistan", "code":"AFG"},
    {"name":"Albania", "code":"ALB"},
    {"name":"Algeria", "code":"DZA"},
    {"name":"Andorra", "code":"AND"},
    {"name":"Angola", "code":"AGO"},
    {"name":"Malta", "code":"MLT"},
    {"name":"Argentina", "code":"ARG"},
    {"name":"Armenia", "code":"ARM"},
    {"name":"Antarctica", "code":"ATA"},
    {"name":"Australia", "code":"AUS"},
    {"name":"Austria", "code":"AUT"},
    {"name":"Azerbaijan", "code":"AZE"},
    {"name":"Bahrain", "code":"BHR"},
    {"name":"Bangladesh", "code":"BGD"},
    {"name":"Belarus", "code":"BLR"},
    {"name":"Belgium", "code":"BEL"},
    {"name":"Belize", "code":"BLZ"},
    {"name":"Benin", "code":"BEN"},
    {"name":"Bhutan", "code":"BTN"},
    {"name":"Bolivia", "code":"BOL"},
    {"name":"Bosnia and Herzegovina", "code":"BIH"},
    {"name":"Botswana", "code":"BWA"},
    {"name":"Brazil", "code":"BRA"},
    {"name":"Brunei", "code":"BRN"},
    {"name":"Bulgaria", "code":"BGR"},
    {"name":"Burkina Faso", "code":"BFA"},
    {"name":"Burundi", "code":"BDI"},
    {"name":"Cambodia", "code":"KHM"},
    {"name":"Cameroon", "code":"CMR"},
    {"name":"Canada", "code":"CAN"},
    {"name":"CAR", "code":"CAF"},
    {"name": "DRC", "code":"COD"},
    {"name":"Chad", "code":"TCD"},
    {"name":"Chile", "code":"CHL"},
    {"name":"China", "code":"CHN"},
    {"name":"Colombia", "code":"COL"},
    {"name":"Congo R", "code":"COG"},
    {"name":"Costa Rica", "code":"CRI"},
    {"name":"South Sudan", "code":"SSD"},
    {"name":"Côte d'Ivoire", "code":"CIV"},
    {"name":"Croatia", "code":"HRV"},
    {"name":"Cuba", "code":"CUB"},
    {"name":"Czechia", "code":"CZE"},
    {"name":"Czech Republic", "code":"CZE"},
    {"name":"Vatican City", "code":"VAT"},
    {"name":"Denmark", "code":"DNK"},
    {"name":"Djibouti", "code":"DJI"},
    {"name":"Ecuador", "code":"ECU"},
    {"name":"Egypt", "code":"EGY"},
    {"name":"El Salvador", "code":"SLV"},
    {"name":"Equatorial Guinea", "code":"GNQ"},
    {"name":"Eritrea", "code":"ERI"},
    {"name":"Estonia", "code":"EST"},
    {"name":"Ethiopia", "code":"ETH"},
    {"name":"Finland", "code":"FIN"},
    {"name":"France", "code":"FRA"},
    {"name":"Gabon", "code":"GAB"},
    {"name":"Gambia", "code":"GMB"},
    {"name":"Georgia", "code":"GEO"},
    {"name":"Germany", "code":"DEU"},
    {"name":"Ghana", "code":"GHA"},
    {"name":"North Macedonia", "code":"MKD"},
    {"name":"Greece", "code":"GRC"},
    {"name":"Guatemala", "code":"GTM"},
    {"name":"Guinea-Bissau", "code":"GNB"},
    {"name":"Honduras", "code":"HND"},
    {"name":"Hungary", "code":"HUN"},
    {"name":"India", "code":"IND"},
    {"name":"Indonesia", "code":"IDN"},
    {"name":"Iran", "code":"IRN"},
    {"name":"Iraq", "code":"IRQ"},
    {"name":"Israel", "code":"ISR"},
    {"name":"Kosovo", "code":"XKX"},
    {"name":"Italy", "code":"ITA"},
    {"name":"Japan", "code":"JPN"},
    {"name":"Jordan", "code":"JOR"},
    {"name":"Kazakhstan", "code":"KAZ"},
    {"name":"Kenya", "code":"KEN"},
    {"name":"North Korea", "code":"PRK"},
    {"name":"Korea", "code":"KOR"},
    {"name":"Kuwait", "code":"KWT"},
    {"name":"Kyrgyzstan", "code":"KGZ"},
    {"name":"Laos", "code":"LAO"},
    {"name":"Latvia", "code":"LVA"},
    {"name":"Lebanon", "code":"LBN"},
    {"name":"Lesotho", "code":"LSO"},
    {"name":"Liberia", "code":"LBR"},
    {"name":"Libya", "code":"LBY"},
    {"name":"South Korea", "code":"KOR"},
    {"name":"Liechtenstein", "code":"LIE"},
    {"name":"Lithuania", "code":"LTU"},
    {"name":"Luxembourg", "code":"LUX"},
    {"name":"Madagascar", "code":"MDG"},
    {"name":"Malawi", "code":"MWI"},
    {"name":"Malaysia", "code":"MYS"},
    {"name":"Mali", "code":"MLI"},
    {"name":"Malta", "code":"MLT"},
    {"name":"Mauritania", "code":"MRT"},
    {"name":"Mexico", "code":"MEX"},
    {"name":"Moldova", "code":"MDA"},
    {"name":"Monaco", "code":"MCO"},
    {"name":"Mongolia", "code":"MNG"},
    {"name":"Montenegro", "code":"MNE"},
    {"name":"Morocco", "code":"MAR"},
    {"name":"Mozambique", "code":"MOZ"},
    {"name":"Myanmar", "code":"MMR"},
    {"name":"Namibia", "code":"NAM"},
    {"name":"Nepal", "code":"NPL"},
    {"name":"Netherlands", "code":"NLD"},
    {"name":"New Zealand", "code":"NZL"},
    {"name":"Nicaragua", "code":"NIC"},
    {"name":"Niger", "code":"NER"},
    {"name":"Nigeria", "code":"NGA"},
    {"name":"Norway", "code":"NOR"},
    {"name":"Oman", "code":"OMN"},
    {"name":"Pakistan", "code":"PAK"},
    {"name":"Palestine", "code":"PSE"},
    {"name":"Panama", "code":"PAN"},
    {"name":"Papua New Guinea", "code":"PNG"},
    {"name":"Paraguay","code":"PRY"},
    {"name":"Peru", "code":"PER"},
    {"name":"Philippines", "code":"PHL"},
    {"name":"Poland", "code":"POL"},
    {"name":"Portugal", "code":"PRT"},
    {"name":"Qatar", "code":"QAT"},
    {"name":"Romania", "code":"ROU"},
    {"name":"Russia", "code":"RUS"},
    {"name":"Rwanda", "code":"RWA"},
    {"name":"San Marino", "code":"SMR"},
    {"name":"Saudi Arabia", "code":"SAU"},
    {"name":"Senegal", "code":"SEN"},
    {"name":"Serbia", "code":"SRB"},
    {"name":"Sierra Leone", "code":"SLE"},
    {"name":"Singapore", "code":"SGP"},
    {"name":"Slovakia", "code":"SVK"},
    {"name":"Slovenia", "code":"SVN"},
    {"name":"Somalia", "code":"SOM"},
    {"name":"South Africa", "code":"ZAF"},
    {"name":"Spain", "code":"ESP"},
    {"name":"Sudan", "code":"SDN"},
    {"name":"Suriname", "code":"SUR"},
    {"name":"Eswatini", "code":"SWZ"},
    {"name":"Sweden", "code":"SWE"},
    {"name":"Switzerland", "code":"CHE"},
    {"name":"Syria", "code":"SYR"},
    {"name":"Taiwan", "code":"TWN"},
    {"name":"Tajikistan", "code":"TJK"},
    {"name":"Tanzania", "code":"TZA"},
    {"name":"Thailand", "code":"THA"},
    {"name":"East Timor", "code":"TLS"},
    {"name":"Togo", "code":"TGO"},
    {"name":"Tunisia", "code":"TUN"},
    {"name":"Turkey", "code":"TUR"},
    {"name":"Turkmenistan", "code":"TKM"},
    {"name":"Uganda", "code":"UGA"},
    {"name":"Ukraine", "code":"UKR"},
    {"name":"UAE", "code":"ARE"},
    {"name":"USA", "code":"USA"},
    {"name":"Uruguay", "code":"URY"},
    {"name":"Uzbekistan", "code":"UZB"},
    {"name":"Venezuela", "code":"VEN"},
    {"name":"Vietnam", "code":"VNM"},
    {"name":"Yemen", "code":"YEM"},
    {"name":"Zambia", "code":"ZMB"},
    {"name":"Zimbabwe", "code":"ZWE"}
]