export const borders: Record<string, string[]> = {
    "Antarctica": ["New Zealand", "South Africa", "Chile"],
    "New Zealand": ["Antarctica", "Australia"],
    "Afghanistan": ["China", "Pakistan", "Tajikistan", "Iran", "Uzbekistan", "Turkmenistan"],
    "Albania": ["Greece", "Kosovo", "Montenegro", "North Macedonia"],
    "Algeria": ["Niger", "Mali", "Morocco", "Tunisia", "Libya", "Mauritania"],
    "Andorra": ["Spain", "France"],
    "Angola": ["Namibia", "DRC", "Congo R", "Zambia"],
    "Argentina": ["Chile", "Paraguay", "Uruguay", "Brazil", "Bolivia"],
    "Armenia": ["Azerbaijan", "Iran", "Turkey", "Georgia"],
    "Australia": ["New Zealand", "Papua New Guinea", "Indonesia"],
    "Austria": ["Germany", "Czechia", "Hungary", "Slovakia", "Slovenia", "Liechtenstein", "Italy", "Switzerland"],
    "Azerbaijan": ["Turkmenistan", "Armenia", "Turkey", "Russia", "Iran", "Georgia"],
    "Bahrain": ["Saudi Arabia"],
    "Bangladesh": ["India"],
    "Belarus": ["Russia", "Lithuania", "Latvia", "Poland", "Ukraine"],
    "Belgium": ["Luxembourg", "Netherlands", "Germany", "France"],
    "Belize": ["Mexico", "Guatemala"],
    "Benin": ["Togo", "Nigeria", "Burkina Faso", "Niger"],
    "Bhutan": ["China", "India"],
    "Burkina Faso": ["Mali", "Cote d'Ivoire", "Niger", "Benin", "Ghana", "Togo"],
    "Bolivia": ["Peru", "Brazil", "Chile", "Paraguay", "Argentina"],
    "Bosnia and Herzegovina": ["Serbia", "Montenegro", "Croatia"],
    "Botswana": ["Namibia", "South Africa", "Zimbabwe", "Zambia"],
    "Brazil": ["Argentina", "France", "Suriname", "Guyana", "Venezuela", "Colombia", "Peru", "Bolivia", "Paraguay", "Uruguay"],
    "Brunei": ["Malaysia"],
    "Bulgaria": ["Romania", "Serbia", "North Macedonia", "Turkey", "Greece"],
    "Burundi": ["Rwanda", "DRC", "Tanzania"],
    "Cambodia": ["Vietnam", "Laos", "Thailand", "Iran", "Uzbekistan", "Turkmenistan"],
    "Cameroon": ["CAR", "Congo R", "Chad", "Equatorial Guinea", "Gabon", "Nigeria"],
    "Canada": ["USA", "Denmark"],
    "North Korea": ["South Korea", "Russia", "China"],
    "CAR": ["Cameroon", "Chad", "DRC", "Congo R", "South Sudan", "Sudan"],
    "Chad": ["Cameroon", "CAR", "Libya", "Niger", "Nigeria", "Sudan"],
    "Chile": ["Antarctica", "Bolivia", "Peru", "Argentina"],
    "China": ["Vietnam", "Laos", "Myanmar", "India", "Nepal", "Bhutan", "Pakistan", "Afghanistan", "Tajikistan", "Kyrgyzstan", "Kazakhstan", "Russia", "Mongolia", "North Korea"],
    "Colombia": ["Venezuela", "Panama", "Peru", "Ecuador", "Brazil"],
    "DRC": ["Angola", "Burundi", "CAR", "Congo R", "Rwanda", "South Sudan", "Tanzania", "Uganda", "Zambia"],
    "Congo R": ["Angola", "Gabon", "CAR", "Cameroon", "DRC"],
    "Costa Rica": ["Panama", "Nicaragua"],
    "Cote d'Ivoire": ["Burkina Faso", "Ghana", "Mali", "Guinea", "Liberia"],
    "Croatia": ["Bosnia and Herzegovina", "Montenegro", "Serbia", "Hungary", "Slovenia"],
    "Cuba": ["Mexico", "USA"],
    "Czechia": ["Germany", "Poland", "Slovakia", "Austria"],
    "Denmark": ["Germany", "Sweden", "Canada"],
    "Djibouti": ["Eritrea", "Ethiopia", "Somalia", "Yemen"],
    "East Timor": ["Indonesia"],
    "Ecuador": ["Peru", "Colombia"],
    "Egypt": ["Libya", "Israel", "Saudi Arabia", "Sudan", "Palestine"],
    "Palestine": ["Egypt", "Jordan"],
    "El Salvador": ["Guatemala", "Honduras"],
    "Equatorial Guinea": ["Cameroon", "Gabon"],
    "Eritrea": ["Djibouti", "Ethiopia", "Sudan"],
    "Estonia": ["Latvia", "Russia"],
    "Eswatini": ["Mozambique", "South Africa"],
    "Ethiopia": ["Djibouti", "Eritrea", "Kenya", "Somalia", "South Sudan", "Sudan"],
    "Finland": ["Norway", "Sweden", "Russia"],
    "France": ["Andorra", "Belgium", "Germany", "Italy", "Luxembourg", "Monaco", "Spain", "Switzerland", "Netherlands", "Suriname", "Brazil"],
    "Gabon": ["Cameroon", "Congo R", "Equatorial Guinea"],
    "Gambia": ["Senegal"],
    "Georgia": ["Armenia", "Azerbaijan", "Russia", "Turkey"],
    "Germany": ["Austria", "Belgium", "Czechia", "Denmark", "France", "Luxembourg", "Netherlands", "Poland", "Switzerland"],
    "Ghana": ["Burkina Faso", "Cote d'Ivoire", "Togo"],
    "Greece": ["Albania", "Bulgaria", "North Macedonia", "Turkey"],
    "Guatemala": ["Belize", "El Salvador", "Honduras", "Mexico"],
    "Guinea": ["Cote d'Ivoire", "Guinea-Bissau", "Liberia", "Mali", "Senegal", "Sierra Leone"],
    "Guinea-Bissau": ["Guinea", "Senegal"],
    "Guyana": ["Brazil", "Suriname", "Venezuela"],
    "Honduras": ["El Salvador", "Guatemala", "Nicaragua"],
    "Hungary": ["Austria", "Croatia", "Romania", "Serbia", "Slovakia", "Slovenia", "Ukraine"],
    "India": ["Bangladesh", "Bhutan", "China", "Myanmar", "Nepal", "Pakistan"],
    "Indonesia": ["East Timor", "Malaysia", "Papua New Guinea", "Australia"],
    "Iran": ["Afghanistan", "Armenia", "Azerbaijan", "Iraq", "Pakistan", "Turkey", "Turkmenistan", "UAE"],
    "Iraq": ["Iran", "Jordan", "Kuwait", "Saudi Arabia", "Syria", "Turkey"],
    "Israel": ["Egypt", "Jordan", "Lebanon", "Syria"],
    "Italy": ["Austria", "France", "San Marino", "Slovenia", "Switzerland", "Vatican City"],
    "Japan": ["Russia", "South Korea"],
    "Jordan": ["Iraq", "Israel", "Saudi Arabia", "Syria", "Palestine"],
    "Kazakhstan": ["China", "Kyrgyzstan", "Russia", "Turkmenistan", "Uzbekistan"],
    "Kenya": ["Ethiopia", "Somalia", "South Sudan", "Tanzania", "Uganda"],
    "Kuwait": ["Iraq", "Saudi Arabia"],
    "Kyrgyzstan": ["China", "Kazakhstan", "Tajikistan", "Uzbekistan"],
    "Laos": ["Cambodia", "China", "Myanmar", "Thailand", "Vietnam"],
    "Latvia": ["Belarus", "Estonia", "Lithuania", "Russia"],
    "Lebanon": ["Israel", "Syria"],
    "Lesotho": ["South Africa"],
    "Liberia": ["Cote d'Ivoire", "Guinea", "Sierra Leone"],
    "Libya": ["Algeria", "Chad", "Egypt", "Niger", "Sudan", "Tunisia"],
    "Liechtenstein": ["Austria", "Switzerland"],
    "Lithuania": ["Belarus", "Latvia", "Poland", "Russia"],
    "Luxembourg": ["Belgium", "France", "Germany"],
    "Malawi": ["Mozambique", "Tanzania", "Zambia"],
    "Malaysia": ["Brunei", "Indonesia", "Thailand"],
    "Mali": ["Algeria", "Burkina Faso", "Cote d'Ivoire", "Guinea", "Mauritania", "Niger", "Senegal"],
    "Mauritania": ["Algeria", "Mali", "Senegal"],
    "Mexico": ["Belize", "Guatemala", "USA", "Cuba"],
    "Moldova": ["Romania", "Ukraine"],
    "Monaco": ["France"],
    "Mongolia": ["China", "Russia"],
    "Montenegro": ["Albania", "Bosnia and Herzegovina", "Croatia", "Kosovo", "Serbia"],
    "Morocco": ["Algeria", "Mauritania", "Spain"],
    "Mozambique": ["Eswatini", "Malawi", "South Africa", "Tanzania", "Zambia", "Zimbabwe"],
    "Myanmar": ["Bangladesh", "China", "India", "Laos", "Thailand"],
    "Namibia": ["Angola", "Botswana", "South Africa", "Zambia"],
    "Nepal": ["China", "India"],
    "Netherlands": ["Belgium", "Germany", "France"],
    "Nicaragua": ["Costa Rica", "Honduras"],
    "Niger": ["Algeria", "Benin", "Burkina Faso", "Chad", "Libya", "Mali", "Nigeria"],
    "Nigeria": ["Benin", "Cameroon", "Chad", "Niger"],
    "North Macedonia": ["Albania", "Bulgaria", "Greece", "Kosovo", "Serbia"],
    "Norway": ["Finland", "Russia", "Sweden"],
    "Oman": ["Saudi Arabia", "UAE", "Yemen"],
    "Pakistan": ["Afghanistan", "China", "India", "Iran"],
    "Panama": ["Colombia", "Costa Rica"],
    "Kosovo": ["Serbia", "Albania", "North Macedonia", "Montenegro"],
    "Papua New Guinea": ["Indonesia", "Australia"],
    "Paraguay": ["Argentina", "Bolivia", "Brazil"],
    "Peru": ["Bolivia", "Brazil", "Chile", "Colombia", "Ecuador"],
    "Poland": ["Belarus", "Czechia ", "Germany", "Lithuania", "Russia", "Slovakia", "Ukraine"],
    "Portugal": ["Spain"],
    "Qatar": ["Saudi Arabia"],
    "Romania": ["Bulgaria", "Hungary", "Moldova", "Serbia", "Ukraine"],
    "Russia": ["Japan", "Azerbaijan", "Belarus", "China", "Estonia", "Finland", "Georgia", "Kazakhstan", "Latvia", "Lithuania", "Mongolia", "Norway", "North Korea", "Poland", "Ukraine", "USA"],
    "Rwanda": ["Burundi", "DRC", "Tanzania", "Uganda"],
    "San Marino": ["Italy"],
    "Saudi Arabia": ["Iraq", "Jordan", "Kuwait", "Oman", "Qatar", "UAE", "Yemen", "Egypt"],
    "Senegal": ["Gambia", "Guinea", "Guinea-Bissau", "Mali", "Mauritania"],
    "Serbia": ["Bosnia and Herzegovina", "Bulgaria", "Croatia", "Hungary", "Kosovo", "Montenegro", "North Macedonia", "Romania"],
    "Sierra Leone": ["Guinea", "Liberia"],
    "Singapore": ["Malaysia"],
    "Slovakia": ["Austria", "Czechia", "Hungary", "Poland", "Ukraine"],
    "Slovenia": ["Austria", "Croatia", "Hungary", "Italy"],
    "Somalia": ["Djibouti", "Ethiopia", "Kenya"],
    "South Korea": ["North Korea", "Japan"],
    "South Africa": ["Botswana", "Eswatini", "Lesotho", "Mozambique", "Namibia", "Zimbabwe", "Antarctica"],
    "South Sudan": ["CAR", "DRC", "Ethiopia", "Kenya", "Sudan", "Uganda"],
    "Spain": ["Andorra", "France", "Gibraltar", "Portugal", "Morocco"],
    "Sudan": ["CAR", "Chad", "Egypt", "Eritrea", "Ethiopia", "Libya", "South Sudan"],
    "Suriname": ["Brazil", "France", "Guyana"],
    "Sweden": ["Finland", "Norway", "Denmark"],
    "Switzerland": ["Austria", "France", "Germany", "Italy", "Liechtenstein"],
    "Syria": ["Iraq", "Israel", "Jordan", "Lebanon", "Turkey"],
    "Tajikistan": ["Afghanistan", "China", "Kyrgyzstan", "Uzbekistan"],
    "Tanzania": ["Burundi", "DRC", "Kenya", "Malawi", "Mozambique", "Rwanda", "Uganda", "Zambia"],
    "Thailand": ["Cambodia", "Laos", "Malaysia", "Myanmar"],
    "Togo": ["Benin", "Burkina Faso", "Ghana"],
    "Tunisia": ["Algeria", "Libya"],
    "Turkey": ["Armenia", "Azerbaijan", "Bulgaria", "Georgia", "Greece", "Iran", "Iraq", "Syria"],
    "Turkmenistan": ["Afghanistan", "Iran", "Kazakhstan", "Uzbekistan", "Azerbaijan"],
    "Uganda": ["DRC", "Kenya", "Rwanda", "South Sudan", "Tanzania"],
    "Ukraine": ["Belarus", "Hungary", "Moldova", "Poland", "Romania", "Russia", "Slovakia"],
    "UAE": ["Oman", "Saudi Arabia", "Iran"],
    "USA": ["Canada", "Mexico", "Russia", "Cuba"],
    "Uruguay": ["Argentina", "Brazil"],
    "Uzbekistan": ["Afghanistan", "Kazakhstan", "Kyrgyzstan", "Tajikistan", "Turkmenistan"],
    "Vatican City": ["Italy"],
    "Venezuela": ["Brazil", "Colombia", "Guyana"],
    "Vietnam": ["Cambodia", "China", "Laos"],
    "Yemen": ["Oman", "Saudi Arabia", "Djibouti"],
    "Zambia": ["Angola", "Botswana", "DRC", "Malawi", "Mozambique", "Namibia", "Tanzania", "Zimbabwe"],
    "Zimbabwe": ["Botswana", "Mozambique", "South Africa", "Zambia"]
}

export function getBorderingCountries(country: string): string[] {
    return borders[country] || [];
}