/*

export const value: Record<string, number> = {
    "Antarctica": 8,
    "New Zealand": 3,
    "Afghanistan": 6,
    "Albania": 3,
    "Algeria": 6,
    "Andorra": 1,
    "Angola": 4,
    "Argentina": 4,
    "Armenia": 2,
    "Australia": 3,
    "Austria": 7,
    "Azerbaijan": 5,
    "Bahrain": 1,
    "Bangladesh": 1,
    "Belarus": 3,
    "Belgium": 2,
    "Belize": 1,
    "Benin": 3,
    "Bhutan": 1,
    "Bolivia": 4,
    "Bosnia and Herzegovina": 3,
    "Botswana": 5,
    "Brazil": 7,
    "Brunei": 1,
    "Bulgaria": 5,
    "Burundi": 3,
    "Cambodia": 3,
    "Cameroon": 4,
    "Canada": 4,
    "North Korea": 2,
    "CAR": 6,
    "Chad": 5,
    "Chile": 5,
    "China": 8,
    "Colombia": 5,
    "DRC": 7,
    "Congo R": 3,
    "Costa Rica": 2,
    "Cote d'Ivoire": 4,
    "Croatia": 4,
    "Cuba": 1,
    "Czechia": 3,
    "Denmark": ["Germany", "Sweden", "Canada"],
    "Djibouti": ["Eritrea", "Ethiopia", "Somalia", "Yemen"],
    "East Timor": ["Indonesia"],
    "Ecuador": ["Peru", "Colombia"],
    "Egypt": ["Libya", "Israel", "Saudi Araba", "Sudan", "Palestine"],
    "Palestine": ["Egypt", "Jordan"],
    "El Salvador": ["Guatemala", "Honduras"],
    "Equatorial Guinea": ["Cameroon", "Gabon"],
    "Eritrea": ["Djibouti", "Ethiopia", "Sudan"],
    "Estonia": ["Latvia", "Russia"],
    "Eswatini": ["Mozambique", "South Africa"],
    "Ethiopia": ["Djibouti", "Eritrea", "Kenya", "Somalia", "South Sudan", "Sudan"],
    "Finland": ["Norway", "Sweden", "Russia"],
    "France": ["Andorra", "Belgium", "Germany", "Italy", "Luxembourg", "Monaco", "Spain", "Switzerland", "Netherlands", "Suriname", "Brazil"],
    "Gabon": ["Cameroon", "Congo R", "Equatorial Guinea"],
    "Gambia": ["Senegal"],
    "Georgia": ["Armenia", "Azerbaijan", "Russia", "Turkey"],
    "Germany": ["Austria", "Belgium", "Czechia", "Denmark", "France", "Luxembourg", "Netherlands", "Poland", "Switzerland"],
    "Ghana": ["Burkina Faso", "Cote d'Ivoire", "Togo"],
    "Greece": ["Albania", "Bulgaria", "North Macedonia", "Turkey"],
    "Guatemala": ["Belize", "El Salvador", "Honduras", "Mexico"],
    "Guinea": ["Cote d'Ivoire", "Guinea-Bissau", "Liberia", "Mali", "Senegal", "Sierra Leone"],
    "Guinea-Bissau": ["Guinea", "Senegal"],
    "Guyana": ["Brazil", "Suriname", "Venezuela"],
    "Honduras": ["El Salvador", "Guatemala", "Nicaragua"],
    "Hungary": ["Austria", "Croatia", "Romania", "Serbia", "Slovakia", "Slovenia", "Ukraine"],
    "India": ["Bangladesh", "Bhutan", "China", "Myanmar", "Nepal", "Pakistan"],
    "Indonesia": ["East Timor", "Malaysia", "Papua New Guinea", "Australia"],
    "Iran": ["Afghanistan", "Armenia", "Azerbaijan", "Iraq", "Pakistan", "Turkey", "Turkmenistan", "UAE"],
    "Iraq": ["Iran", "Jordan", "Kuwait", "Saudi Arabia", "Syria", "Turkey"],
    "Israel": ["Egypt", "Jordan", "Lebanon", "Syria"],
    "Italy": ["Austria", "France", "San Marino", "Slovenia", "Switzerland", "Vatican City"],
    "Japan": ["Russia", "South Korea"],
    "Jordan": ["Iraq", "Israel", "Saudi Arabia", "Syria", "Palestine"],
    "Kazakhstan": ["China", "Kyrgyzstan", "Russia", "Turkmenistan", "Uzbekistan"],
    "Kenya": ["Ethiopia", "Somalia", "South Sudan", "Tanzania", "Uganda"],
    "Kuwait": ["Iraq", "Saudi Arabia"],
    "Kyrgyzstan": ["China", "Kazakhstan", "Tajikistan", "Uzbekistan"],
    "Laos": ["Cambodia", "China", "Myanmar", "Thailand", "Vietnam"],
    "Latvia": ["Belarus", "Estonia", "Lithuania", "Russia"],
    "Lebanon": ["Israel", "Syria"],
    "Lesotho": ["South Africa"],
    "Liberia": ["Cote d'Ivoire", "Guinea", "Sierra Leone"],
    "Libya": ["Algeria", "Chad", "Egypt", "Niger", "Sudan", "Tunisia"],
    "Liechtenstein": ["Austria", "Switzerland"],
    "Lithuania": ["Belarus", "Latvia", "Poland", "Russia"],
    "Luxembourg": ["Belgium", "France", "Germany"],
    "Malawi": ["Mozambique", "Tanzania", "Zambia"],
    "Malaysia": ["Brunei", "Indonesia", "Thailand"],
    "Mali": ["Algeria", "Burkina Faso", "Cote d'Ivoire", "Guinea", "Mauritania", "Niger", "Senegal"],
    "Mauritania": ["Algeria", "Mali", "Senegal"],
    "Mexico": ["Belize", "Guatemala", "USA", "Cuba"],
    "Moldova": ["Romania", "Ukraine"],
    "Monaco": ["France"],
    "Mongolia": ["China", "Russia"],
    "Montenegro": ["Albania", "Bosnia and Herzegovina", "Croatia", "Kosovo", "Serbia"],
    "Morocco": ["Algeria", "Mauritania", "Spain"],
    "Mozambique": ["Eswatini", "Malawi", "South Africa", "Tanzania", "Zambia", "Zimbabwe"],
    "Myanmar": ["Bangladesh", "China", "India", "Laos", "Thailand"],
    "Namibia": ["Angola", "Botswana", "South Africa", "Zambia"],
    "Nepal": ["China", "India"],
    "Netherlands": ["Belgium", "Germany", "France"],
    "Nicaragua": ["Costa Rica", "Honduras"],
    "Niger": ["Algeria", "Benin", "Burkina Faso", "Chad", "Libya", "Mali", "Nigeria"],
    "Nigeria": ["Benin", "Cameroon", "Chad", "Niger"],
    "North Macedonia": ["Albania", "Bulgaria", "Greece", "Kosovo", "Serbia"],
    "Norway": ["Finland", "Russia", "Sweden"],
    "Oman": ["Saudi Arabia", "UAE", "Yemen"],
    "Pakistan": ["Afghanistan", "China", "India", "Iran"],
    "Panama": ["Colombia", "Costa Rica"],
    "Kosovo": ["Serbia", "Albania", "North Macedonia", "Montenegro"],
    "Papua New Guinea": ["Indonesia", "Australia"],
    "Paraguay": ["Argentina", "Bolivia", "Brazil"],
    "Peru": ["Bolivia", "Brazil", "Chile", "Colombia", "Ecuador"],
    "Poland": ["Belarus", "Czechia ", "Germany", "Lithuania", "Russia", "Slovakia", "Ukraine"],
    "Portugal": ["Spain"],
    "Qatar": ["Saudi Arabia"],
    "Romania": ["Bulgaria", "Hungary", "Moldova", "Serbia", "Ukraine"],
    "Russia": ["Japan", "Azerbaijan", "Belarus", "China", "Estonia", "Finland", "Georgia", "Kazakhstan", "Latvia", "Lithuania", "Mongolia", "Norway", "North Korea", "Poland", "Ukraine", "USA"],
    "Rwanda": ["Burundi", "DRC", "Tanzania", "Uganda"],
    "San Marino": ["Italy"],
    "Saudi Arabia": ["Iraq", "Jordan", "Kuwait", "Oman", "Qatar", "UAE", "Yemen", "Egypt"],
    "Senegal": ["Gambia", "Guinea", "Guinea-Bissau", "Mali", "Mauritania"],
    "Serbia": ["Bosnia and Herzegovina", "Bulgaria", "Croatia", "Hungary", "Kosovo", "Montenegro", "North Macedonia", "Romania"],
    "Sierra Leone": ["Guinea", "Liberia"],
    "Singapore": ["Malaysia"],
    "Slovakia": ["Austria", "Czechia", "Hungary", "Poland", "Ukraine"],
    "Slovenia": ["Austria", "Croatia", "Hungary", "Italy"],
    "Somalia": ["Djibouti", "Ethiopia", "Kenya"],
    "South Korea": ["North Korea", "Japan"],
    "South Africa": ["Botswana", "Eswatini", "Lesotho", "Mozambique", "Namibia", "Zimbabwe", "Antarctica"],
    "South Sudan": ["CAR", "DRC", "Ethiopia", "Kenya", "Sudan", "Uganda"],
    "Spain": ["Andorra", "France", "Gibraltar", "Portugal", "Morocco"],
    "Sudan": ["CAR", "Chad", "Egypt", "Eritrea", "Ethiopia", "Libya", "South Sudan"],
    "Suriname": ["Brazil", "France", "Guyana"],
    "Sweden": ["Finland", "Norway", "Denmark"],
    "Switzerland": ["Austria", "France", "Germany", "Italy", "Liechtenstein"],
    "Syria": ["Iraq", "Israel", "Jordan", "Lebanon", "Turkey"],
    "Tajikistan": ["Afghanistan", "China", "Kyrgyzstan", "Uzbekistan"],
    "Tanzania": ["Burundi", "DRC", "Kenya", "Malawi", "Mozambique", "Rwanda", "Uganda", "Zambia"],
    "Thailand": ["Cambodia", "Laos", "Malaysia", "Myanmar"],
    "Timor-Leste": ["Indonesia"],
    "Togo": ["Benin", "Burkina Faso", "Ghana"],
    "Tunisia": ["Algeria", "Libya"],
    "Turkey": ["Armenia", "Azerbaijan", "Bulgaria", "Georgia", "Greece", "Iran", "Iraq", "Syria"],
    "Turkmenistan": ["Afghanistan", "Iran", "Kazakhstan", "Uzbekistan", "Azerbaijan"],
    "Uganda": ["DRC", "Kenya", "Rwanda", "South Sudan", "Tanzania"],
    "Ukraine": ["Belarus", "Hungary", "Moldova", "Poland", "Romania", "Russia", "Slovakia"],
    "UAE": ["Oman", "Saudi Arabia", "Iran"],
    "USA": ["Canada", "Mexico", "Russia", "Cuba"],
    "Uruguay": ["Argentina", "Brazil"],
    "Uzbekistan": ["Afghanistan", "Kazakhstan", "Kyrgyzstan", "Tajikistan", "Turkmenistan"],
    "Vatican City": ["Italy"],
    "Venezuela": ["Brazil", "Colombia", "Guyana"],
    "Vietnam": ["Cambodia", "China", "Laos"],
    "Yemen": ["Oman", "Saudi Arabia", "Djibouti"],
    "Zambia": ["Angola", "Botswana", "DRC", "Malawi", "Mozambique", "Namibia", "Tanzania", "Zimbabwe"],
    "Zimbabwe": ["Botswana", "Mozambique", "South Africa", "Zambia"]
}

*/